apiVersion: v1
kind: Pod
metadata:
  name: crash
spec:
  containers:
    - name: app
      image: distroless-app:dev
      imagePullPolicy: Never
      args: ["-exit"]
      resources:
        limits:
          cpu: 200m
          memory: 32Mi
