worker_processes auto;
events { worker_connections 8192; }
error_log /results/error.log;
error_log /results/error-info.log info;
http {
  log_format rl '$msec $request_time $status $uri $http_x_tenant "$upstream_addr" "$upstream_status" "$upstream_connect_time" "$upstream_header_time" "$upstream_response_time" $request_id';
  access_log /results/access.log rl;

  limit_req_zone $http_x_tenant zone=tenant:1m rate=50r/s;
  limit_req_zone all zone=fixed:1m rate=160r/s;
  limit_req_status 429;

  upstream app {
    zone app 64k;
    server app:8081;
  }

  server {
    listen 80;
    location /api/ {
      limit_req zone=tenant burst=20 nodelay;
      limit_req zone=fixed burst=20 nodelay;
      proxy_pass http://app;
      proxy_set_header X-Request-Id $request_id;
      proxy_read_timeout 1s;
    }
  }
}
